// Generated from Texto colado.txt. Edit the pasted source and regenerate if the roster changes.
window.ALBUM_PLAYER_TEAMS = [
    {
        "group":  "A",
        "code":  "MEX",
        "country":  "México",
        "players":  [
                        "Luis Malagón",
                        "Johan Vásquez",
                        "Jorge Sánchez",
                        "César Montes",
                        "Jesús Gallardo",
                        "Israel Reyes",
                        "Diego Lainez",
                        "Carlos Rodríguez",
                        "Edson Álvarez",
                        "Orbelín Pineda",
                        "Marcel Ruiz",
                        "Érick Sánchez",
                        "Hirving Lozano",
                        "Santiago Giménez",
                        "Raúl Jiménez",
                        "Alexis Vega",
                        "Roberto Alvarado",
                        "César Huerta"
                    ]
    },
    {
        "group":  "A",
        "code":  "RSA",
        "country":  "África do Sul",
        "players":  [
                        "Ronwen Williams",
                        "Sipho Chaine",
                        "Aubrey Modiba",
                        "Samukele Kabini",
                        "Mbekezeli Mbokazi",
                        "Khulumani Ndamane",
                        "Siyabonga Ngezana",
                        "Khuliso Mudau",
                        "Nkosinathi Sibisi",
                        "Teboho Mokoena",
                        "Thalente Mbatha",
                        "Bathuisi Aubaas",
                        "Yaya Sithole",
                        "Sipho Mbule",
                        "Lyle Foster",
                        "Ioraam Rayners",
                        "Mohau Nkota",
                        "Oswin Appolis"
                    ]
    },
    {
        "group":  "A",
        "code":  "KOR",
        "country":  "Coreia do Sul",
        "players":  [
                        "Hyeon-woo Jo",
                        "Seung-Gyu Kim",
                        "Min-jae Kim",
                        "Yu-min Cho",
                        "Young-woo Seol",
                        "Han-beom Lee",
                        "Tae-seok Lee",
                        "Myung-jae Lee",
                        "Jae-sung Lee",
                        "In-beom Hwang",
                        "Kang-in Lee",
                        "Seung-ho Paik",
                        "Jens Castrop",
                        "Dong-gyeong Lee",
                        "Gue-sung Cho",
                        "Heung-min Son",
                        "Hee-chan Hwang",
                        "Hyeon-Gyu Oh"
                    ]
    },
    {
        "group":  "A",
        "code":  "CZE",
        "country":  "República Tcheca",
        "players":  [
                        "Matěj Kovář",
                        "Jindřich Staněk",
                        "Ladislav Krejčí",
                        "Vladimír Coufal",
                        "Jaroslav Zelený",
                        "Tomáš Holeš",
                        "David Zima",
                        "Michal Sadílek",
                        "Lukáš Provod",
                        "Lukáš Červ",
                        "Tomáš Souček",
                        "Pavel Šulc",
                        "Matěj Vydra",
                        "Vasil Kušej",
                        "Tomáš Chorý",
                        "Václav Černý",
                        "Adam Hložek",
                        "Patrik Schick"
                    ]
    },
    {
        "group":  "B",
        "code":  "CAN",
        "country":  "Canadá",
        "players":  [
                        "Dayne St. Clair",
                        "Alphonso Davies",
                        "Alistair Johnston",
                        "Samuel Adekugbe",
                        "Richie Laryea",
                        "Derek Cornelius",
                        "Moïse Bombito",
                        "Kamal Miller",
                        "Stephen Eustáquio",
                        "Ismaël Koné",
                        "Jonathan Osorio",
                        "Jacob Shaffelburg",
                        "Mathieu Choinière",
                        "Niko Sigur",
                        "Tajon Buchanan",
                        "Liam Millar",
                        "Cyle Larin",
                        "Jonathan David"
                    ]
    },
    {
        "group":  "B",
        "code":  "BIH",
        "country":  "Bósnia e Herzegovina",
        "players":  [
                        "Nikola Vasilj",
                        "Amar Dedić",
                        "Sead Kolašinac",
                        "Tarik Muharemović",
                        "Nihad Mujakić",
                        "Nikola Katić",
                        "Amir Hadžiahmetović",
                        "Benjamin Tahirović",
                        "Armin Gigović",
                        "Ivan Šunjić",
                        "Ivan Bašić",
                        "Dženis Burnić",
                        "Esmir Bajraktarević",
                        "Amar Memić",
                        "Ermedin Demirović",
                        "Edin Džeko",
                        "Samed Baždar",
                        "Haris Tabaković"
                    ]
    },
    {
        "group":  "B",
        "code":  "QAT",
        "country":  "Catar",
        "players":  [
                        "Meshaal Barsham",
                        "Sultan Albrake",
                        "Lucas Mendes",
                        "Homam Ahmed",
                        "Boualem Khoukhi",
                        "Pedro Miguel",
                        "Tarek Salman",
                        "Mohamed Al-Mannai",
                        "Karim Boudiaf",
                        "Assim Madibo",
                        "Ahmed Fatehi",
                        "Mohammed Waad",
                        "Abdulaziz Hatem",
                        "Hassan Al-Haydos",
                        "Edmilson Junior",
                        "Akram Hassan Afif",
                        "Ahmed Al Ganehi",
                        "Almoez Ali"
                    ]
    },
    {
        "group":  "B",
        "code":  "SUI",
        "country":  "Suíça",
        "players":  [
                        "Gregor Kobel",
                        "Yvon Mvogo",
                        "Manuel Akanji",
                        "Ricardo Rodriguez",
                        "Nico Elvedi",
                        "Aurèle Amenda",
                        "Silvan Widmer",
                        "Granit Xhaka",
                        "Denis Zakaria",
                        "Remo Freuler",
                        "Fabian Rieder",
                        "Ardon Jashari",
                        "Johan Manzambi",
                        "Michel Aebischer",
                        "Breel Embolo",
                        "Ruben Vargas",
                        "Dan Ndoye",
                        "Zeki Amdouni"
                    ]
    },
    {
        "group":  "C",
        "code":  "BRA",
        "country":  "Brasil",
        "players":  [
                        "Alisson",
                        "Bento",
                        "Marquinhos",
                        "Éder Militão",
                        "Gabriel Magalhães",
                        "Danilo",
                        "Wesley",
                        "Lucas Paquetá",
                        "Casemiro",
                        "Bruno Guimarães",
                        "Luiz Henrique",
                        "Vinícius Júnior",
                        "Rodrygo",
                        "João Pedro",
                        "Matheus Cunha",
                        "Gabriel Martinelli",
                        "Raphinha",
                        "Estêvão"
                    ]
    },
    {
        "group":  "C",
        "code":  "MAR",
        "country":  "Marrocos",
        "players":  [
                        "Yassine Bounou",
                        "Munir El Kajoui",
                        "Achraf Hakimi",
                        "Noussair Mazraoui",
                        "Nayef Aguerd",
                        "Romain Saïss",
                        "Jawad El Yamiq",
                        "Adam Masina",
                        "Sofyan Amrabat",
                        "Azzedine Ounahi",
                        "Eliesse Ben Seghir",
                        "Bilal El Khannouss",
                        "Ismael Saibari",
                        "Youssef En-Nesyri",
                        "Abde Ezzalzouli",
                        "Soufiane Rahimi",
                        "Brahim Díaz",
                        "Ayoub El Kaabi"
                    ]
    },
    {
        "group":  "C",
        "code":  "HAI",
        "country":  "Haiti",
        "players":  [
                        "Johny Placide",
                        "Carlens Arcus",
                        "Martin Expérience",
                        "Jean-Kevin Duverne",
                        "Ricardo Adé",
                        "Duke Lacroix",
                        "Garven Metusala",
                        "Hannes Delcroix",
                        "Leverton Pierre",
                        "Danley Jean Jacques",
                        "Jean-Ricner Bellegarde",
                        "Christopher Attys",
                        "Derrick Etienne Jr.",
                        "Josué Casimir",
                        "Ruben Providence",
                        "Duckens Nazon",
                        "Louicius Deedson",
                        "Frantzdy Pierrot"
                    ]
    },
    {
        "group":  "C",
        "code":  "SCO",
        "country":  "Escócia",
        "players":  [
                        "Angus Gunn",
                        "Jack Hendry",
                        "Kieran Tierney",
                        "Aaron Hickey",
                        "Andrew Robertson",
                        "Scott McKenna",
                        "John Souttar",
                        "Anthony Ralston",
                        "Grant Hanley",
                        "Scott McTominay",
                        "Billy Gilmour",
                        "Lewis Ferguson",
                        "Ryan Christie",
                        "Kenny McLean",
                        "John McGinn",
                        "Lyndon Dykes",
                        "Che Adams",
                        "Ben Gannon-Doak"
                    ]
    },
    {
        "group":  "D",
        "code":  "USA",
        "country":  "Estados Unidos",
        "players":  [
                        "Math Freese",
                        "Chris Richards",
                        "Tim Ream",
                        "Mark McKenzie",
                        "Alex Freeman",
                        "Antonee Robinson",
                        "Tyler Adams",
                        "Tanner Tessmann",
                        "Weston McKenny",
                        "Christian Roldan",
                        "Timothy Weah",
                        "Diego Luna",
                        "Malim Tillman",
                        "Christian Pulisic",
                        "Brenden Aaronson",
                        "Ricardo Pepi",
                        "Haji Wright",
                        "Folarin Balogun"
                    ]
    },
    {
        "group":  "D",
        "code":  "PAR",
        "country":  "Paraguai",
        "players":  [
                        "Roberto Fernández",
                        "Orlando Gill",
                        "Gustavo Gómez",
                        "Fabián Balbuena",
                        "Juan José Cáceres",
                        "Omar Alderete",
                        "Junior Alonso",
                        "Mathías Villasanti",
                        "Diego Gómez",
                        "Damián Bobadilla",
                        "Andrés Cubas",
                        "Matías Galarza Fonda",
                        "Julio Enciso"
                    ]
    },
    {
        "group":  "D",
        "code":  "AUS",
        "country":  "Austrália",
        "players":  [
                        "Mathew Ryan",
                        "Joe Gauci",
                        "Harry Souttar",
                        "Alessandro Circati",
                        "Jordan Bos",
                        "Aziz Behich",
                        "Cameron Burgess",
                        "Lewis Miller",
                        "Milos Degenek",
                        "Jackson Irvine",
                        "Riley McGree",
                        "Aiden O’Neill",
                        "Connor Metcalfe",
                        "Patrick Yazbek",
                        "Craig Goodwin",
                        "Kusini Yengi",
                        "Nestory Irankunda",
                        "Mohamed Touré"
                    ]
    },
    {
        "group":  "D",
        "code":  "TUR",
        "country":  "Turquia",
        "players":  [
                        "Ugurcan Cakir",
                        "Mert Muldur",
                        "Zeki Celik",
                        "Abdulkerim Bardakci",
                        "Caglar Soyunku",
                        "Merih Demiral",
                        "Ferdi Kadioglu",
                        "Kaan Ayhan",
                        "Ismail Yuksek",
                        "Hakan Calhanoglu",
                        "Orkun Kokcu",
                        "Arda Güler",
                        "Irfan Can Kahvecu",
                        "Yunus Akgun",
                        "Can Uzun",
                        "Baris Alper Yilmaz",
                        "Kerem Akturkoglu",
                        "Kenan Yildiz"
                    ]
    },
    {
        "group":  "E",
        "code":  "GER",
        "country":  "Alemanha",
        "players":  [
                        "Marc-André ter Stegen",
                        "Jonathan Tah",
                        "David Raum",
                        "Nico Schlotterbeck",
                        "Antonio Rüdiger",
                        "Waldemar Anton",
                        "Ridle Baku",
                        "Maximilian Mittelstädt",
                        "Joshua Kimmich",
                        "Florian Wirtz",
                        "Felix Nmecha",
                        "Leon Goretzka",
                        "Jamal Musiala",
                        "Serge Gnabry",
                        "Kai Havertz",
                        "Leroy Sané",
                        "Karim Adeyemi",
                        "Nick Woltemade"
                    ]
    },
    {
        "group":  "E",
        "code":  "CUW",
        "country":  "Curaçao",
        "players":  [
                        "Eloy Room",
                        "Armando Obispo",
                        "Sherel Floranus",
                        "Jurien Gaari",
                        "Joshua Brenet",
                        "Roshon Van Eijma",
                        "Shurandy Sambo",
                        "Livano Comenencia",
                        "Godfried Roemeratoe",
                        "Juninho Bacuna",
                        "Leandro Bacuna",
                        "Tahith Chong",
                        "Kenji Gorré",
                        "Jearl Margaritha",
                        "Jurgen Locadia",
                        "Jeremy Antonisse",
                        "Gervane Kastaneer",
                        "Sontje Hansen"
                    ]
    },
    {
        "group":  "E",
        "code":  "CIV",
        "country":  "Costa do Marfim",
        "players":  [
                        "Yahia Fofana",
                        "Ghislain Konan",
                        "Wilfried Singo",
                        "Odilon Kossounou",
                        "Evan Ndicka",
                        "Willy Boly",
                        "Emmanuel Agbadou",
                        "Ousmane Diomande",
                        "Franck Kessié",
                        "Seko Fofana",
                        "Ibrahim Sangaré",
                        "Jean-Philippe Gbamin",
                        "Amad Diallo",
                        "Sébastien Haller",
                        "Simon Adingra",
                        "Yan Diomande",
                        "Evann Guessand",
                        "Oumar Diakité"
                    ]
    },
    {
        "group":  "E",
        "code":  "ECU",
        "country":  "Equador",
        "players":  [
                        "Hernán Galíndez",
                        "Gonzalo Valle",
                        "Piero Hincapié",
                        "Pervis Estupiñán",
                        "Willian Pacho",
                        "Ángelo Preciado",
                        "Joel Ordóñez",
                        "Moisés Caicedo",
                        "Alan Franco",
                        "Kendry Páez",
                        "Pedro Vite",
                        "John Veboah",
                        "Leonardo Campana",
                        "Gonzalo Plata",
                        "Nilson Angulo",
                        "Alan Minda",
                        "Kevin Rodríguez",
                        "Enner Valencia"
                    ]
    },
    {
        "group":  "F",
        "code":  "NED",
        "country":  "Holanda",
        "players":  [
                        "Bart Verbruggen",
                        "Virgil van Dijk",
                        "Micky van de Ven",
                        "Jurriën Timber",
                        "Denzel Dumfries",
                        "Nathan Aké",
                        "Jeremie Frimpong",
                        "Jan Paul van Hecke",
                        "Tijjani Reijnders",
                        "Ryan Gravenberch",
                        "Teun Koopmeiners",
                        "Frenkie de Jong",
                        "Xavi Simons",
                        "Justin Kluivert",
                        "Memphis Depay",
                        "Donyell Malen",
                        "Wout Weghorst",
                        "Cody Gakpo"
                    ]
    },
    {
        "group":  "F",
        "code":  "JPN",
        "country":  "Japão",
        "players":  [
                        "Zion Suzuki",
                        "Henry Heroki Mochizuki",
                        "Ayumu Seko",
                        "Junnosuke Suzuki",
                        "Shogo Taniguchi",
                        "Tsuyoshi Watanabe",
                        "Kaishu Sano",
                        "Yuki Soma",
                        "Ao Tanaka",
                        "Daichi Kamada",
                        "Takefusa Kubo",
                        "Ritsu Doan",
                        "Keito Nakamura",
                        "Takumi Minamino",
                        "Shuto Machino",
                        "Junya Ito",
                        "Koki Ogawa",
                        "Ayase Ueda"
                    ]
    },
    {
        "group":  "F",
        "code":  "SWE",
        "country":  "Suécia",
        "players":  [
                        "Victor Johansson",
                        "Isak Hien",
                        "Gabriel Gudmundsson",
                        "Emil Holm",
                        "Victor Nilsson Lindelöf",
                        "Gustaf Lagerbielke",
                        "Lucas Bergvall",
                        "Hugo Larsson",
                        "Jesper Karlström",
                        "Yasin Ayari",
                        "Mattias Svanberg",
                        "Daniel Svensson",
                        "Ken Sema",
                        "Roony Bardghji",
                        "Dejan Kulusevski",
                        "Anthony Elanga",
                        "Alexander Isak",
                        "Viktor Gyökeres"
                    ]
    },
    {
        "group":  "F",
        "code":  "TUN",
        "country":  "Tunísia",
        "players":  [
                        "Bechir Ben Said",
                        "Aymen Dahmen",
                        "Van Valery",
                        "Montassar Talbi",
                        "Yassine Meriah",
                        "Ali Abdi",
                        "Dylan Bronn",
                        "Ellyes Skhiri",
                        "Aissa Laidouni",
                        "Ferjani Sassi",
                        "Mohamed Ali Ben Romdhane",
                        "Hannibal Mejbri",
                        "Elias Achouri",
                        "Elias Saad",
                        "Hazem Mastouri",
                        "Ismael Gharbi",
                        "Sayfallah Ltaief",
                        "Naim Sliti"
                    ]
    },
    {
        "group":  "G",
        "code":  "BEL",
        "country":  "Bélgica",
        "players":  [
                        "Thibaut Courtois",
                        "Arthur Theate",
                        "Timothy Castagne",
                        "Zeno Debast",
                        "Brandon Mechele",
                        "Maxim De Cuyper",
                        "Thomas Meunier",
                        "Youri Tielemans",
                        "Amadou Onana",
                        "Nicolas Raskin",
                        "Alexis Saelemaekers",
                        "Hans Vanaken",
                        "Kevin De Bruyne",
                        "Jérémy Doku",
                        "Charles De Ketelaere",
                        "Leandro Trossard",
                        "Loïs Openda",
                        "Romelu Lukaku"
                    ]
    },
    {
        "group":  "G",
        "code":  "EGY",
        "country":  "Egito",
        "players":  [
                        "Mohamed El Shenawy",
                        "Mohamed Hany",
                        "Mohamed Hamdy",
                        "Yasser Ibrahim",
                        "Khaled Sobhi",
                        "Ramy Rabia",
                        "Hossam Abdelmaguid",
                        "Ahmed Fatouh",
                        "Marwan Attia",
                        "Zizo",
                        "Hamdy Fathy",
                        "Mohamed Lasheen",
                        "Emam Ashour",
                        "Osama Faisal",
                        "Mohamed Salah",
                        "Mostafa Mohamed",
                        "Trezeguet",
                        "Omar Marmoush"
                    ]
    },
    {
        "group":  "G",
        "code":  "IRN",
        "country":  "Irã",
        "players":  [
                        "Alireza Beiranvand",
                        "Morteza Pouraliganji",
                        "Ehsan Hajsafi",
                        "Milad Mohammadi",
                        "Shoja Khalilzadeh",
                        "Ramin Rezaeian",
                        "Hossein Kanaani",
                        "Sadegh Moharrami",
                        "Saleh Hardani",
                        "Saeed Ezatolahi",
                        "Saman Ghoddos",
                        "Omid Noorafkan",
                        "Roozbeh Cheshmi",
                        "Mohammad Mohebi",
                        "Sardar Azmoun",
                        "Mehdi Taremi",
                        "Alireza Jahanbakhsh",
                        "Ali Gholizadeh"
                    ]
    },
    {
        "group":  "G",
        "code":  "NZL",
        "country":  "Nova Zelândia",
        "players":  [
                        "Max Crocombe-Payne",
                        "Alex Paulsen",
                        "Michael Boxall",
                        "Liberato Cacace",
                        "Tim Payne",
                        "Tyler Bindon",
                        "Francis de Vries",
                        "Finn Surman",
                        "Joe Bell",
                        "Sarpreet Singh",
                        "Ryan Thomas",
                        "Matthew Garbett",
                        "Marko Stamenić",
                        "Ben Old",
                        "Chris Wood",
                        "Elijah Just",
                        "Callum McCowatt",
                        "Kosta Barbarouses"
                    ]
    },
    {
        "group":  "H",
        "code":  "ESP",
        "country":  "Espanha",
        "players":  [
                        "Unai Simón",
                        "Robin Le Normand",
                        "Aymeric Laporte",
                        "Dean Huijsen",
                        "Pedro Porro",
                        "Dani Carvajal",
                        "Marc Cucurella",
                        "Martín Zubimendi",
                        "Rodri",
                        "Pedri",
                        "Fabián Ruiz",
                        "Mikel Merino",
                        "Lamine Yamal",
                        "Dani Olmo",
                        "Nico Williams",
                        "Ferran Torres",
                        "Álvaro Morata",
                        "Mikel Oyarzabal"
                    ]
    },
    {
        "group":  "H",
        "code":  "CPV",
        "country":  "Cabo Verde",
        "players":  [
                        "Vozinha",
                        "Logan Costa",
                        "Pico",
                        "Diney",
                        "Steven Moreira",
                        "Wagner Pina",
                        "João Paulo",
                        "Yannick Semedo",
                        "Kevin Pina",
                        "Patrick Andrade",
                        "Jamiro Monteiro",
                        "Deroy Duarte",
                        "Garry Rodrigues",
                        "Jovane Cabral",
                        "Ryan Mendes",
                        "Dailon Livramento",
                        "Willy Semedo",
                        "Bebé"
                    ]
    },
    {
        "group":  "H",
        "code":  "KSA",
        "country":  "Arábia Saudita",
        "players":  [
                        "Nawaf Alaqidi",
                        "Abdulrahman Al-Sanbi",
                        "Saud Abdulhamid",
                        "Nawaf Boushal",
                        "Jihad Thakri",
                        "Moteb Al-Harbi",
                        "Hassan Altambakti",
                        "Musab Aljuwayr",
                        "Ziyad Aljohani",
                        "Abdullah Alkhaibari",
                        "Nasser Aldawsari",
                        "Saleh Abu Alshamat",
                        "Marwan Alsahafi",
                        "Salem Aldawsari",
                        "Abdulrahman Al-Aboud",
                        "Feras Albrikan",
                        "Saleh Alshehri",
                        "Abdullah Al-Hamdan"
                    ]
    },
    {
        "group":  "H",
        "code":  "URU",
        "country":  "Uruguai",
        "players":  [
                        "Sergio Rochet",
                        "Santiago Mele",
                        "Ronald Araujo",
                        "José María Giménez",
                        "Sebastian Caceres",
                        "Mathias Olivera",
                        "Guillermo Varela",
                        "Nahitan Nandez",
                        "Federico Valverde",
                        "Giorgian De Arrascaeta",
                        "Rodrigo Bentancur",
                        "Manuel Ugarte",
                        "Nicolás de la Cruz",
                        "Maxi Araujo",
                        "Darwin Núñez",
                        "Federico Viñas",
                        "Rodrigo Aguirre",
                        "Facundo Pellistri"
                    ]
    },
    {
        "group":  "I",
        "code":  "FRA",
        "country":  "França",
        "players":  [
                        "Mike Maignan",
                        "Theo Hernández",
                        "William Saliba",
                        "Jules Koundé",
                        "Ibrahima Konaté",
                        "Dayot Upamecano",
                        "Lucas Digne",
                        "Aurélien Tchouaméni",
                        "Eduardo Camavinga",
                        "Manu Koné",
                        "Adrien Rabiot",
                        "Michael Olise",
                        "Ousmane Dembélé",
                        "Bradley Barcola",
                        "Désiré Doué",
                        "Kingsley Coman",
                        "Hugo Ekitike",
                        "Kylian Mbappé"
                    ]
    },
    {
        "group":  "I",
        "code":  "SEN",
        "country":  "Senegal",
        "players":  [
                        "Eduardo Mendy",
                        "Yehvann Diouf",
                        "Moussa Niakhaté",
                        "Abdoulaye Seck",
                        "Ismail Jakobs",
                        "El Hadji Malick Diouf",
                        "Kalidou Koulibaly",
                        "Idrissa Gana Gueye",
                        "Pape Matar Sarr",
                        "Pape Gueye",
                        "Habib Diarra",
                        "Lamine Camara",
                        "Sadio Mane",
                        "Ismaïla Sarr",
                        "Boulaye Dia",
                        "Iliman Ndiaye",
                        "Nicolas Jackson",
                        "Krepin Diatta"
                    ]
    },
    {
        "group":  "I",
        "code":  "IRQ",
        "country":  "Iraque",
        "players":  [
                        "Jalal Hassan",
                        "Rebin Sulaka",
                        "Hussein Ali",
                        "Akam Hashem",
                        "Merchas Doski",
                        "Zaid Tahseen",
                        "Manaf Younis",
                        "Zidane Iqbal",
                        "Amir Al-Ammari",
                        "Ibrahim Bayesh",
                        "Ali Jasim",
                        "Youssef Amyn",
                        "Aimar Sher",
                        "Marko Farji",
                        "Osama Rashid",
                        "Ali Al-Hamadi",
                        "Aymen Hussein",
                        "Mohanad Ali"
                    ]
    },
    {
        "group":  "I",
        "code":  "NOR",
        "country":  "Noruega",
        "players":  [
                        "Ørjan Nyland",
                        "Julian Ryerson",
                        "Leo Østigård",
                        "Kristoffer Ajer",
                        "Marcus Holmgren Pedersen",
                        "David Møller Wolfe",
                        "Torbjørn Heggem",
                        "Morten Thorsby",
                        "Martin Ødegaard",
                        "Sander Berge",
                        "Andreas Schjelderup",
                        "Patrick Berg",
                        "Erling Haaland",
                        "Alexander Sørloth",
                        "Aron Dønnum",
                        "Jørgen Strand Larsen",
                        "Antonio Nusa",
                        "Oscar Bobb"
                    ]
    },
    {
        "group":  "J",
        "code":  "ARG",
        "country":  "Argentina",
        "players":  [
                        "Emiliano Martínez",
                        "Nahuel Molina",
                        "Cristian Romero",
                        "Nicolás Otamendi",
                        "Nicolás Tagliafico",
                        "Leonardo Balerdi",
                        "Enzo Fernández",
                        "Alexis Mac Allister",
                        "Rodrigo De Paul",
                        "Exequiel Palacios",
                        "Leandro Paredes",
                        "Nico Paz",
                        "Franco Mastantuono",
                        "Nico González",
                        "Lionel Messi",
                        "Lautaro Martínez",
                        "Julián Álvarez",
                        "Giuliano Simeone"
                    ]
    },
    {
        "group":  "J",
        "code":  "ALG",
        "country":  "Argélia",
        "players":  [
                        "Alexis Guendouz",
                        "Ramy Bensebaini",
                        "Youcef Atal",
                        "Rayan Aït-Nouri",
                        "Mohamed Amine Tougai",
                        "Aïssa Mandi",
                        "Ismael Bennacer",
                        "Houssem Aouar",
                        "Hicham Boudaoui",
                        "Ramiz Zerrouki",
                        "Nabil Bentaleb",
                        "Farés Chaibi",
                        "Riyad Mahrez",
                        "Said Benrahma",
                        "Anis Hadj Moussa",
                        "Amine Gouiri",
                        "Baghdad Bounedjah",
                        "Mohammed Amoura"
                    ]
    },
    {
        "group":  "J",
        "code":  "AUT",
        "country":  "Áustria",
        "players":  [
                        "Alexander Schlager",
                        "Patrick Pentz",
                        "David Alaba",
                        "Kevin Danso",
                        "Philipp Lienhart",
                        "Stefan Posch",
                        "Phillipp Mwene",
                        "Alexander Prass",
                        "Xaver Schlager",
                        "Marcel Sabitzer",
                        "Konrad Laimer",
                        "Florian Grillitsch",
                        "Nicolas Seiwald",
                        "Romano Schmid",
                        "Patrick Wimmer",
                        "Christoph Baumgartner",
                        "Michael Gregoritsch",
                        "Marko Arnautović"
                    ]
    },
    {
        "group":  "J",
        "code":  "JOR",
        "country":  "Jordânia",
        "players":  [
                        "Yazeed Abulaila",
                        "Ihsan Haddad",
                        "Mohammad Abu Hashish",
                        "Yazan Al-Arab",
                        "Abdallah Nasib",
                        "Saleem Obaid",
                        "Mohammad Abualnadi",
                        "Ibrahim Saadeh",
                        "Nizar Al-Rashdan",
                        "Noor Al-Rawabdeh",
                        "Mohannad Abu Taha",
                        "Amer Jamous",
                        "Musa Al-Taamari",
                        "Yazan Al-Naimat",
                        "Mahmoud Al-Mardi",
                        "Ali Olwan",
                        "Mohammad Abu Zrayq",
                        "Ibrahim Sabra"
                    ]
    },
    {
        "group":  "K",
        "code":  "POR",
        "country":  "Portugal",
        "players":  [
                        "Diogo Costa",
                        "Jose Sa",
                        "Ruben Dias",
                        "João Cancelo",
                        "Diogo Dalot",
                        "Nuno Mendes",
                        "Gonçalo Inácio",
                        "Bernardo Silva",
                        "Bruno Fernandes",
                        "Ruben Neves",
                        "Vitinha",
                        "João Neves",
                        "Cristiano Ronaldo",
                        "Francisco Trincão",
                        "João Felix",
                        "Gonçalo Ramos",
                        "Pedro Neto",
                        "Rafael Leão"
                    ]
    },
    {
        "group":  "K",
        "code":  "COD",
        "country":  "RD Congo",
        "players":  [
                        "Lionel Mpasi",
                        "Aaron Wan-Bissaka",
                        "Axel Tuanzebe",
                        "Arthur Masuaku",
                        "Chancel Mbemba",
                        "Joris Kayembe",
                        "Charles Pickel",
                        "Ngal’ayel Mukau",
                        "Edo Kayembe",
                        "Samuel Moutoussamy",
                        "Noah Sadiki",
                        "Théo Bongonda",
                        "Meschack Elia",
                        "Yoane Wissa",
                        "Brian Cipenga",
                        "Fiston Mayele",
                        "Cédric Bakambu",
                        "Nathanaël Mbuku"
                    ]
    },
    {
        "group":  "K",
        "code":  "UZB",
        "country":  "Uzbequistão",
        "players":  [
                        "Utkir Yusupov",
                        "Farrukh Savfiev",
                        "Sherzod Nasrullaev",
                        "Umar Eshmurodov",
                        "Husniddin Aliqulov",
                        "Rustamjon Ashurmatov",
                        "Khojiakbar Alijonov",
                        "Abdukodir Khusanov",
                        "Odiljon Hamrobekov",
                        "Otabek Shukurov",
                        "Jamshid Iskanderov",
                        "Azizbek Turgunboev",
                        "Khojimat Erkinov",
                        "Eldor Shomurodov",
                        "Oston Urunov",
                        "Jaloliddin Masharipov",
                        "Igor Sergeev",
                        "Abbosbek Fayzullaev"
                    ]
    },
    {
        "group":  "K",
        "code":  "COL",
        "country":  "Colômbia",
        "players":  [
                        "Camilo Vargas",
                        "David Ospina",
                        "Dávinson Sánchez",
                        "Yerry Mina",
                        "Daniel Muñoz",
                        "Johan Mojica",
                        "Jhon Lucumí",
                        "Santiago Arias",
                        "Jefferson Lerma",
                        "Kevin Castaño",
                        "Richard Ríos",
                        "James Rodríguez",
                        "Juan Fernando Quintero",
                        "Jorge Carrascal",
                        "Jhon Arias",
                        "Jhon Córdoba",
                        "Luis Suárez",
                        "Luis Díaz"
                    ]
    },
    {
        "group":  "L",
        "code":  "ENG",
        "country":  "Inglaterra",
        "players":  [
                        "Jordan Pickford",
                        "John Stones",
                        "Marc Guéhi",
                        "Ezri Konsa",
                        "Trent Alexander-Arnold",
                        "Reece James",
                        "Dan Burn",
                        "Jordan Henderson",
                        "Declan Rice",
                        "Jude Bellingham",
                        "Cole Palmer",
                        "Morgan Rogers",
                        "Anthony Gordon",
                        "Phil Foden",
                        "Bukayo Saka",
                        "Harry Kane",
                        "Marcus Rashford",
                        "Ollie Watkins"
                    ]
    },
    {
        "group":  "L",
        "code":  "CRO",
        "country":  "Croácia",
        "players":  [
                        "Dominik Livaković",
                        "Duje Ćaleta-Car",
                        "Joško Gvardiol",
                        "Josip Stanišić",
                        "Luka Vušković",
                        "Josip Šutalo",
                        "Kristijan Jakić",
                        "Luka Modrić",
                        "Mateo Kovačić",
                        "Martin Baturina",
                        "Lovro Majer",
                        "Mario Pašalić",
                        "Petar Sučić",
                        "Ivan Perišić",
                        "Marco Pašalić",
                        "Ante Budimir",
                        "Andrej Kramarić",
                        "Franjo Ivanović"
                    ]
    },
    {
        "group":  "L",
        "code":  "GHA",
        "country":  "Gana",
        "players":  [
                        "Lawrence Ati Zigi",
                        "Tariq Lamptey",
                        "Mohammed Salisu",
                        "Alidu Seidu",
                        "Alexander Djiku",
                        "Gideon Mensah",
                        "Caleb Yirenkyi",
                        "Abdul Fatawu Issahaku",
                        "Thomas Partey",
                        "Salis Abdul Samed",
                        "Kamaldeen Sulemana",
                        "Mohammed Kudus",
                        "Iñaki Williams",
                        "Jordan Ayew",
                        "André Ayew",
                        "Joseph Paintsil",
                        "Osman Bukari",
                        "Antoine Semenyo"
                    ]
    },
    {
        "group":  "L",
        "code":  "PAN",
        "country":  "Panamá",
        "players":  [
                        "Orlando Mosquera",
                        "Luis Mejía",
                        "Fidel Escobar",
                        "Andrés Andrade",
                        "Michael Amir Murillo",
                        "Eric Davis",
                        "José Córdoba",
                        "César Blackman",
                        "Cristian Martínez",
                        "Aníbal Godoy",
                        "Adalberto Carrasquilla",
                        "Édgar Bárcenas",
                        "Carlos Harvey",
                        "Ismael Díaz",
                        "José Fajardo",
                        "Cecilio Waterman",
                        "José Luis Rodríguez",
                        "Alberto Quintero"
                    ]
    }
];

window.ALBUM_PLAYER_AUDIT = {
    "generatedAt":  "2026-05-31T01:01:37.8692934Z",
    "source":  "Texto colado.txt",
    "groups":  12,
    "teams":  48,
    "players":  859,
    "expectedPlayersIf18PerTeam":  864,
    "corrections":  [
                        {
                            "country":  "Escócia",
                            "from":  [
                                         "Billy GilmourLewis",
                                         "Ferguson"
                                     ],
                            "to":  [
                                       "Billy Gilmour",
                                       "Lewis Ferguson"
                                   ]
                        }
                    ],
    "warnings":  [
                     {
                         "country":  "Paraguai",
                         "code":  "PAR",
                         "players":  13,
                         "expected":  18
                     }
                 ]
};
